export default {
  ROLES: [
    "Director", "Producer", "Production Manager", "Technical Director",
    "Actor", "Improvisor", "Stage Manager", "Community Wellness Coordinator",
    "Intimacy Director", "Choreographer (Dance)", "Choreographer (Combat)",
    "Choreographer (Other)", "Lighting Designer", "Sound Designer",
    "Multimedia/Projections Designer", "Graphic Designer", "Costume Designer",
    "Set Designer", "Prop Master", "Writer", "Deviser", "Dramaturg",
    "Music Director", "Vocal Director", "Board Operator",
    "Hair and Makeup", "General Run Crew", "Musical Improvisor", "Musician",
    "Singer/Vocalist", "Composer", "Dancer", "Drag Artist"
  ].sort(),
  MUSICAL_ROLES: ["Musical Improvisor", "Musician"],
  INSTRUMENTS: [
    "Accordion",
    "Guitar (acoustic)",
    "Alto saxophone",
    "Bagpipes",
    "Banjo",
    "Bass guitar",
    "Bassoon",
    "Cello",
    "Clarinet",
    "Double bass",
    "Drums",
    "Guitar (electric)",
    "Flute",
    "French horn",
    "Harp",
    "Harpsichord",
    "Keyboard",
    "Mandolin",
    "Marimba",
    "Oboe",
    "Organ",
    "Piano",
    "Piccolo",
    "Recorder",
    "Sitar",
    "Synthesizer",
    "Trombone",
    "Trumpet",
    "Tuba",
    "Ukulele",
    "Viola",
    "Violin",
    "Xylophone",
    "Bass clarinet",
    "Bass trombone",
    "Celesta",
    "Contrabassoon",
    "English horn",
    "Euphonium",
    "Glockenspiel",
    "Percussion",
    "Piccolo trumpet",
    "Soprano saxophone",
    "Tenor saxophone",
    "Timpani",
    "Triangle",
    "Tubular bells",
  ].sort(),  
  WAYS_TO_LEARN: [
    "Workshop",
    "Assistant role",
    "Casual 1-on-1 with student"
  ].sort(),
  YEARS: [2024, 2025, 2026, 2027, 2028, 2029, 2030],
  AFFILIATIONS: ["Undergraduate", "Graduate", "Coterm", "Faculty", "Staff"]
}