export default {
  ROLES: [
    "Director", 
    "Assistant Directory", 
    "Producer", 
    "Production Manager", 
    "Technical Director",
    "Actor", 
    "Improvisor",
    "Stage Manager", 
    "Community Wellness Coordinator",
    "Intimacy Director", 
    "Choreographer (Dance)", 
    "Choreographer (Combat)",
    "Choreographer (Other)", 
    "Lighting Designer",
    "Sound Designer",
    "Multimedia/Projections Designer", 
    "Graphic Designer", 
    "Costume Designer",
    "Set Designer", 
    "Set Builder", 
    "Prop Master", 
    "Writer", 
    "Playwright",
    "Screenwriter",
    "Deviser", 
    "Dramaturg",
    "Music Director", 
    "Vocal Director", 
    "Board Operator",
    "Hair and Makeup", 
    "General Run Crew", 
    "Musical Improvisor", 
    "Musician",
    "Singer/Vocalist", 
    "Composer", 
    "Dancer", 
    "Drag Artist", 
    "Script Supervisor",
    "Puppeteer", 
    "Puppet Builder",
    "Casting Director",
    "Cinematographer",
    "Production Designer",
    "Art Director",
    "Gaffer",
    "Boom Operator",
    "Foley Artist",
    "Production Assistant",
    "Director of Photography",
    "Camera Operator",
    "Key Grip",
    "Tailor",
    "Stunt Coordinator",
    "Stunt Performer",
    "VFX Artist",
    "Colorist",
    "Voice Actor"
  ].sort(),
  MUSICAL_ROLES: ["Musical Improvisor", "Musician"],
  INSTRUMENTS: [
    "Accordion",
    "Guitar (acoustic)",
    "Alto saxophone",
    "Bagpipes",
    "Banjo",
    "Bass guitar",
    "Bassoon",
    "Cello",
    "Clarinet",
    "Double bass",
    "Drums",
    "Guitar (electric)",
    "Flute",
    "French horn",
    "Harp",
    "Harpsichord",
    "Keyboard",
    "Mandolin",
    "Marimba",
    "Oboe",
    "Organ",
    "Piano",
    "Piccolo",
    "Recorder",
    "Sitar",
    "Synthesizer",
    "Trombone",
    "Trumpet",
    "Tuba",
    "Ukulele",
    "Viola",
    "Violin",
    "Xylophone",
    "Bass clarinet",
    "Bass trombone",
    "Celesta",
    "Contrabassoon",
    "English horn",
    "Euphonium",
    "Glockenspiel",
    "Percussion",
    "Piccolo trumpet",
    "Soprano saxophone",
    "Tenor saxophone",
    "Timpani",
    "Triangle",
    "Tubular bells",
  ].sort(),  
  WAYS_TO_LEARN: [
    "Workshop",
    "Assistant role",
    "Casual 1-on-1 with student"
  ].sort(),
  YEARS: [2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030],
  AFFILIATIONS: ["Undergraduate", "Graduate", "Coterm", "Faculty", "Staff"]
}